# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbalance',
            name='card_no',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
