# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20170328_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbalance',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardbalance',
            name='irc_no',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
